import type { Metadata } from 'next'
import './globals.css'

import { Inter } from 'next/font/google'

import { ClerkProvider } from '@clerk/nextjs'

import Nav from '../components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className='min-h-screen'>
          <Nav />
          <div className='flex justify-center items-center p-24'>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}


export default RootLayout